language: python
sudo: required
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"

matrix:
  fast_finish: true

jobs:
  include:
  - stage: format-check
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - black --check --diff .

  - stage: deploy
    if: tag IS present
    python: "3.6"
    install: skip
    script: skip
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      distributions: sdist bdist_wheel
      on:
        tags: true

# command to install dependencies
install:
  - "pip install -r testing-requirements.txt"
# command to run tests
script:
  - tests/run_tests.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
